# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chenshijian/OrderBook_Engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chenshijian/OrderBook_Engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chenshijian/OrderBook_Engine/CMakeFiles /home/chenshijian/OrderBook_Engine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chenshijian/OrderBook_Engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OrderBook_Engine

# Build rule for target.
OrderBook_Engine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OrderBook_Engine
.PHONY : OrderBook_Engine

# fast build rule for target.
OrderBook_Engine/fast:
	$(MAKE) -f CMakeFiles/OrderBook_Engine.dir/build.make CMakeFiles/OrderBook_Engine.dir/build
.PHONY : OrderBook_Engine/fast

Book.o: Book.cpp.o

.PHONY : Book.o

# target to build an object file
Book.cpp.o:
	$(MAKE) -f CMakeFiles/OrderBook_Engine.dir/build.make CMakeFiles/OrderBook_Engine.dir/Book.cpp.o
.PHONY : Book.cpp.o

Book.i: Book.cpp.i

.PHONY : Book.i

# target to preprocess a source file
Book.cpp.i:
	$(MAKE) -f CMakeFiles/OrderBook_Engine.dir/build.make CMakeFiles/OrderBook_Engine.dir/Book.cpp.i
.PHONY : Book.cpp.i

Book.s: Book.cpp.s

.PHONY : Book.s

# target to generate assembly for a file
Book.cpp.s:
	$(MAKE) -f CMakeFiles/OrderBook_Engine.dir/build.make CMakeFiles/OrderBook_Engine.dir/Book.cpp.s
.PHONY : Book.cpp.s

CreateOrder.o: CreateOrder.cpp.o

.PHONY : CreateOrder.o

# target to build an object file
CreateOrder.cpp.o:
	$(MAKE) -f CMakeFiles/OrderBook_Engine.dir/build.make CMakeFiles/OrderBook_Engine.dir/CreateOrder.cpp.o
.PHONY : CreateOrder.cpp.o

CreateOrder.i: CreateOrder.cpp.i

.PHONY : CreateOrder.i

# target to preprocess a source file
CreateOrder.cpp.i:
	$(MAKE) -f CMakeFiles/OrderBook_Engine.dir/build.make CMakeFiles/OrderBook_Engine.dir/CreateOrder.cpp.i
.PHONY : CreateOrder.cpp.i

CreateOrder.s: CreateOrder.cpp.s

.PHONY : CreateOrder.s

# target to generate assembly for a file
CreateOrder.cpp.s:
	$(MAKE) -f CMakeFiles/OrderBook_Engine.dir/build.make CMakeFiles/OrderBook_Engine.dir/CreateOrder.cpp.s
.PHONY : CreateOrder.cpp.s

Engine.o: Engine.cpp.o

.PHONY : Engine.o

# target to build an object file
Engine.cpp.o:
	$(MAKE) -f CMakeFiles/OrderBook_Engine.dir/build.make CMakeFiles/OrderBook_Engine.dir/Engine.cpp.o
.PHONY : Engine.cpp.o

Engine.i: Engine.cpp.i

.PHONY : Engine.i

# target to preprocess a source file
Engine.cpp.i:
	$(MAKE) -f CMakeFiles/OrderBook_Engine.dir/build.make CMakeFiles/OrderBook_Engine.dir/Engine.cpp.i
.PHONY : Engine.cpp.i

Engine.s: Engine.cpp.s

.PHONY : Engine.s

# target to generate assembly for a file
Engine.cpp.s:
	$(MAKE) -f CMakeFiles/OrderBook_Engine.dir/build.make CMakeFiles/OrderBook_Engine.dir/Engine.cpp.s
.PHONY : Engine.cpp.s

Logger.o: Logger.cpp.o

.PHONY : Logger.o

# target to build an object file
Logger.cpp.o:
	$(MAKE) -f CMakeFiles/OrderBook_Engine.dir/build.make CMakeFiles/OrderBook_Engine.dir/Logger.cpp.o
.PHONY : Logger.cpp.o

Logger.i: Logger.cpp.i

.PHONY : Logger.i

# target to preprocess a source file
Logger.cpp.i:
	$(MAKE) -f CMakeFiles/OrderBook_Engine.dir/build.make CMakeFiles/OrderBook_Engine.dir/Logger.cpp.i
.PHONY : Logger.cpp.i

Logger.s: Logger.cpp.s

.PHONY : Logger.s

# target to generate assembly for a file
Logger.cpp.s:
	$(MAKE) -f CMakeFiles/OrderBook_Engine.dir/build.make CMakeFiles/OrderBook_Engine.dir/Logger.cpp.s
.PHONY : Logger.cpp.s

Order.o: Order.cpp.o

.PHONY : Order.o

# target to build an object file
Order.cpp.o:
	$(MAKE) -f CMakeFiles/OrderBook_Engine.dir/build.make CMakeFiles/OrderBook_Engine.dir/Order.cpp.o
.PHONY : Order.cpp.o

Order.i: Order.cpp.i

.PHONY : Order.i

# target to preprocess a source file
Order.cpp.i:
	$(MAKE) -f CMakeFiles/OrderBook_Engine.dir/build.make CMakeFiles/OrderBook_Engine.dir/Order.cpp.i
.PHONY : Order.cpp.i

Order.s: Order.cpp.s

.PHONY : Order.s

# target to generate assembly for a file
Order.cpp.s:
	$(MAKE) -f CMakeFiles/OrderBook_Engine.dir/build.make CMakeFiles/OrderBook_Engine.dir/Order.cpp.s
.PHONY : Order.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/OrderBook_Engine.dir/build.make CMakeFiles/OrderBook_Engine.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/OrderBook_Engine.dir/build.make CMakeFiles/OrderBook_Engine.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/OrderBook_Engine.dir/build.make CMakeFiles/OrderBook_Engine.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... OrderBook_Engine"
	@echo "... edit_cache"
	@echo "... Book.o"
	@echo "... Book.i"
	@echo "... Book.s"
	@echo "... CreateOrder.o"
	@echo "... CreateOrder.i"
	@echo "... CreateOrder.s"
	@echo "... Engine.o"
	@echo "... Engine.i"
	@echo "... Engine.s"
	@echo "... Logger.o"
	@echo "... Logger.i"
	@echo "... Logger.s"
	@echo "... Order.o"
	@echo "... Order.i"
	@echo "... Order.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

